### ISSUE TITLE
Corruption of legacy database

### ISSUE THREAD

**Issue by titpetric** [maxmind/geoip-api-java#40]
Hey,

I'm still one of the users of the legacy database. I came across this error when handling the latest GeoIP.dat file:

~~~
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.ByteBuffer.wrap(ByteBuffer.java:371)
        at com.maxmind.geoip.LookupService.readRecordBuf(LookupService.java:751)
        at com.maxmind.geoip.LookupService.readCityRecord(LookupService.java:718)
        at com.maxmind.geoip.LookupService.getLocation(LookupService.java:708)
        at com.maxmind.geoip.LookupService.getLocation(LookupService.java:615)
        at com.maxmind.geoip.LookupService.getLocation(LookupService.java:627)
        at com.titpetric.wse.module.GeoIPLookupService.GetCountry(GeoIPLookupService.java:38)
        at com.titpetric.wse.module.GeoIPTest.main(GeoIPTest.java:18)
~~~

This is when using LookupService.GEOIP_MEMORY_CACHE. When changing this to GEOIP_STANDARD the exception goes away, but no IPs are resolved (getCountry returns '--'). Is it possible that the current database published is corrupted somehow?

**Comment by oschwald** [comment]
What version of the API are you using? I believe there was a bug fixed in 1.3.0 that could cause a similar issue. If you are not using 1.3.1, would you be able to re-test with that?

**Comment by titpetric** [comment]
I am using 1.3.1, and I just verified that the above works with the GeoLite City database.

**Comment by titpetric** [comment]
I also verified that GeoLite Country works with the PHP api (and doesn't with GeoLite City). I'll read some more documentation, maybe I missed something obvious how the databases differ (ie, if there's a different reader for Country/City databases).

**Comment by titpetric** [comment]
Yeah, it seems to be exactly that. `getLocation` is for GeoLite City, and `getCountry` is for GeoLite Country.

1. Is it somehow possible to detect which database somebody uses, to degrade some capabilities here? File header, BOM, something?
2. Would you be willing to accept a PR along these lines if this is possible, to partially fill out Location data with just Country details?
3. Is this repository "frozen" or what does "legacy" mean in this case? Is there some sort of phase-out/EOL planned for these legacy databases?

I'm pretty sure `readCityRecord` should throw some kind of exception if `databaseType` is COUNTRY_EDITION (or it should degrade to fill out only available data from getCountry) - either is enough for some compatibility...

**Comment by oschwald** [comment]
It should be possible to distinguish between a City and Country database by looking at the metadata at the end of the database. I think I would prefer a PR that threw an exception if the wrong method was used to one that partially filled in the data.

"Legacy" currently means that we are not actively adding features to these APIs beyond bug fixes, but we are willing to accept reasonable, backwards-compatible enhancements to them. No EOL date for the legacy databases has been set yet, but we will likely announce one in the near future.

**Comment by titpetric** [comment]
I'm willing to give it a stab if you're willing to give me some general instructions/background so I can correctly check the markers for a city/country db.

Also relevant would be the behavior of getCountry() against the City database - if it returns a country with it, I would argue to fill out getLocation country data partially.

**Comment by oschwald** [comment]
It appears there is already [this code](https://github.com/maxmind/geoip-api-java/blob/9cbd7dcc23659b6e486939823380c110a26b9b90/src/main/java/com/maxmind/geoip/LookupService.java#L310) that should determine the database type and set `databaseType`. Perhaps all that is needed is appropriate checks in the method calls.

`getCountry()` does not work with the City database.

**Comment by oschwald** [comment]
I am closing this due to lack of activity. Our future development is focused on the GeoIP2 reader, which does verify the right database type is being used before reading.
